# This workflow will build and push a PHP application to an Azure Web App when a commit is pushed to your default branch.
# Last Updated: 26.08.2024  |   Created : 26.08.2024
# 

name: Build and deploy Kabooxa App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  KABOOXA_WEBAPP_NAME: kabooxa    # set this to your application's name
  KABOOXA_WEBAPP_PACKAGE_PATH: '/home/kabooxa/test.kabooxa.net'      # set this to the path to your web app project, defaults to the repository root
  KABOOXA_WEBAPP_HOST: '173.231.248.175' # IP address of the server
  KABOOXA_WEBAPP_USERNAME: 'root' #USERNAME 
  KABOOXA_WEBAPP_PASSWORD: ''  #PASSWORD
  KABOOXA_WEBAPP_PORT: 22
  PHP_VERSION: '8.x'                  # set this to the PHP version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: 
            whoami
            echo "Hi"
          timeout: 120s
